name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: envoyproxy/envoy-build-ubuntu:latest
      options: -v /bazel:/bazel
    steps:
    - uses: actions/checkout@v1
    - name: Bazel disk cache
      uses: actions/cache@v1
      with:
        path: /bazel/cache
        key: /bazel/cache
    - name: Build
      run: bazel --output_base=/bazel build --disk_cache=/bazel/cache //futon:futon.tar
    - name: Upload docker image tar
      uses: actions/upload-artifact@v1
      with:
        name: futon-${{ github.sha }}.tar
        path: bazel-bin/futon/futon.tar
