name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: envoyproxy/envoy-build-ubuntu:latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: bazel build //futon:futon.tar
    - name: debug
      run: readlink -m bazel-bin
#     - name: Upload docker image tar
#       uses: actions/upload-artifact@v1
#       with:
#         name: futon-${{ github.sha }}.tar
#         path: bazel-bin/futon/futon.tar
