name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Bazel disk cache
      uses: actions/cache@v1
      with:
        path: bazel/cache
        key: /bazel/cache  # this could be any constant
    - name: Build
      uses: docker://envoyproxy/envoy-build-ubuntu:latest
      with:
        args: bazel --output_base=bazel build --disk_cache=bazel/cache //futon:futon.tar
    - name: debug
      run: readlink -m bazel-bin &&
        ls bazel/execroot && 
        ls bazel/execroot/futon &&
        ls bazel/execroot/futon/bazel-out &&
        ls bazel/execroot/futon/bazel-out/k8-fastbuild &&
        ls bazel/execroot/futon/bazel-out/k8-fastbuild/bin &&
        ls bazel/execroot/futon/bazel-out/k8-fastbuild/bin/futon
    - name: Docker push
      run: docker load -i bazel-bin/futon/futon.tar &&
        docker login --username connorworley --password '${{ secrets.DOCKER_HUB_PASSWORD }}' &&
        docker tag bazel/futon:futon connorworley/futon:latest &&
        docker tag bazel/futon:futon connorworley/futon:${{ github.sha }} &&
        docker push connorworley/futon:latest &&
        docker push connorworley/futon:${{ github.sha }}
